### ISSUE TITLE
for vlc 

### ISSUE THREAD

**Issue by ssamin69** [byte-capsule/TSports-m3u8-Grabber#1]
please add instructions for how to use on vlc player if its possible

**Comment by byte-capsule** [comment]
This playlist doesn't work in Vlc.....
You can use it.
https://github.com/byte-capsule/AynaOTT-Hls-Fetcher
It works on Vlc
👍

**Comment by ssamin69** [comment]
> This playlist doesn't work in Vlc.....
> You can use it.
> https://github.com/byte-capsule/AynaOTT-Hls-Fetcher
> It works on Vlc
> 👍

bro it says channels are off on that playlist

**Comment by byte-capsule** [comment]
Aynaott added header protection to their streams.....this is why Aynaott no longer works on VLC.....🤧

**Comment by ssamin69** [comment]
> Aynaott added header protection to their streams.....this is why Aynaott no longer works on VLC.....🤧

do you know any alternatives to watch at least tsports on any linux devices?

**Comment by byte-capsule** [comment]
https://chromewebstore.google.com/detail/modheader-modify-http-hea/idgpnmonknjnojddfkpgkljpfnnfcklj

Add this extension to Chrome.....and set referrer value https://watch.aynaott.com/

then open it https://byte-capsule-2x.onrender.com/api/aynaott/sign?channel_id=tsportsfhd


![IMG_20240215_102353_905](https://github.com/byte-capsule/TSports-m3u8-Grabber/assets/79209625/7299f8e4-daf1-4633-b427-643e6f6c49fd)

**Comment by ssamin69** [comment]
> https://modheader.com/
> 
> Add this extension to Chrome.....and set referer value https://watch.aynaott.com/
> 
> then open it https://byte-capsule-2x.onrender.com/api/aynaott/sign?channel_id=tsportsfhd
> 
> 
> ![IMG_20240215_102353_905](https://github.com/byte-capsule/TSports-m3u8-Grabber/assets/79209625/7299f8e4-daf1-4633-b427-643e6f6c49fd)
> 

doesn't work

**Comment by byte-capsule** [comment]
It seems you didn't add the referrer properly......plz try it again.....
or u can use NS Player App on emulator

**Comment by ssamin69** [comment]
> It seems you didn't add the referrer properly......plz try it again.....
> or u can use NS Player App on emulator

are you sure this works for you? cause i added the referer as you showed still gives me error 
![Screenshot_20240219_190125_Kiwi Browser.jpg](https://github.com/byte-capsule/TSports-m3u8-Grabber/assets/72408262/255a533b-5c3b-47f9-80fa-95f523be5061)

**Comment by ssamin69** [comment]
> It seems you didn't add the referrer properly......plz try it again.....
> or u can use NS Player App on emulator



can you please elaborate on how this "NS" player works? is there any other players that can play m3u8 playlists with http headers?
